# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_errors.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlg_errors(object):
    def setupUi(self, dlg_errors):
        dlg_errors.setObjectName("dlg_errors")
        dlg_errors.resize(648, 676)
        self.ted_errors = QtWidgets.QPlainTextEdit(dlg_errors)
        self.ted_errors.setGeometry(QtCore.QRect(10, 10, 631, 661))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ted_errors.setFont(font)
        self.ted_errors.setObjectName("ted_errors")

        self.retranslateUi(dlg_errors)
        QtCore.QMetaObject.connectSlotsByName(dlg_errors)

    def retranslateUi(self, dlg_errors):
        _translate = QtCore.QCoreApplication.translate
        dlg_errors.setWindowTitle(_translate("dlg_errors", "Dialog"))
